# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='rank',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
