# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 16:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_section_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/news<function file_folder_allocator at 0x7f2c9baea578>'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file_upload',
            field=models.FileField(upload_to='files/notices/<function file_folder_allocator at 0x7f2c9baea578>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/posts/<function file_folder_allocator at 0x7f2c9baea578>'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_upload',
            field=models.FileField(upload_to='files/resources/<function file_folder_allocator at 0x7f2c9baea578>'),
        ),
    ]
